import{addDoc,collection,doc,getDoc,getDocs,query,runTransaction,serverTimestamp,setDoc,updateDoc,where}from'firebase/firestore';

export const DEFAULT_COURSES=[
{id:'financial-foundations',title:'Financial Foundations',audience:'customer',category:'Foundations',description:'Learn how AFG accounts, balances, goals, and fictional financial decisions work.',passingScore:70,xp:100,lessons:[{title:'The AFG economy',body:'AFG is a fictional economy. Balances have no cash value and all profile information must remain fictional.'},{title:'Accounts and goals',body:'Checking supports everyday activity while savings supports longer-term goals.'}],questions:[{prompt:'Are AFG balances real money?',options:['Yes','No'],answer:1},{prompt:'Which account is designed for longer-term goals?',options:['Checking','Savings'],answer:1}]},
{id:'responsible-borrowing',title:'Responsible Borrowing',audience:'customer',category:'Borrowing',description:'Understand fictional loans, interest, payments, and account standing.',passingScore:75,xp:125,lessons:[{title:'Borrowing basics',body:'A loan creates an obligation that must be repaid according to its approved terms.'},{title:'Payment performance',body:'On-time fictional payments support a stronger Trust Score and customer standing.'}],questions:[{prompt:'What should happen after accepting a fictional loan?',options:['Ignore it','Follow the payment schedule'],answer:1},{prompt:'On-time payments generally help which system?',options:['Trust Score','Discord username'],answer:0}]},
{id:'afg-orientation',title:'AFG Staff Orientation',audience:'staff',category:'Onboarding',description:'Required introduction to AFG structure, staff conduct, and portal responsibilities.',passingScore:80,xp:150,required:true,lessons:[{title:'Institution structure',body:'Rank determines authority, department determines responsibility, branch determines assignment, and permissions determine exact access.'},{title:'Staff conduct',body:'Staff must protect customer information, avoid conflicts of interest, and document privileged actions.'}],questions:[{prompt:'What determines exact system access?',options:['Permissions','Display name'],answer:0},{prompt:'Can staff process their own customer records?',options:['Yes','No'],answer:1}]},
{id:'customer-privacy',title:'Customer Privacy & Safety',audience:'staff',category:'Compliance',description:'Protect customer information and enforce the fictional-information requirement.',passingScore:85,xp:175,required:true,lessons:[{title:'Information boundaries',body:'Customer-private records are restricted. Real financial documents and identity uploads are prohibited.'},{title:'Need-to-know access',body:'Staff should access only records required for assigned duties.'}],questions:[{prompt:'Are document uploads available?',options:['Yes','No'],answer:1},{prompt:'Should staff access unrelated customer records?',options:['Yes','No'],answer:1}]}
];
const map=s=>s.docs.map(d=>({id:d.id,...d.data()}));
export async function seedDefaultCourses(db,uid){const existing=await getDocs(collection(db,'academyCourses'));if(existing.size)return;await Promise.all(DEFAULT_COURSES.map(c=>setDoc(doc(db,'academyCourses',c.id),{...c,active:true,createdBy:uid,createdAt:serverTimestamp(),updatedAt:serverTimestamp()})));}
export async function loadAcademy(db,uid){const[b,u,p,sp,c,e,cert,a]=await Promise.all([getDoc(doc(db,'system','bootstrap')),getDoc(doc(db,'users',uid)),getDoc(doc(db,'staffPermissions',uid)),getDoc(doc(db,'staffProfiles',uid)),getDocs(collection(db,'academyCourses')),getDocs(query(collection(db,'academyEnrollments'),where('userUid','==',uid))),getDocs(query(collection(db,'academyCertificates'),where('userUid','==',uid))),getDocs(query(collection(db,'trainingAssignments'),where('staffUid','==',uid)))]);const isOwner=b.exists()&&b.data().ownerUid===uid;const permissions=p.exists()?p.data().permissions||[]:[];return{isOwner,user:u.data(),staff:sp.exists()?sp.data():null,permissions,courses:map(c).filter(x=>x.active!==false),enrollments:map(e),certificates:map(cert),assignments:map(a),canManage:isOwner||permissions.some(x=>['training.manage','academy.manage','staff.manage','owner.override_all'].includes(x))};}
export async function enroll(db,uid,course){const id=`${uid}_${course.id}`;await setDoc(doc(db,'academyEnrollments',id),{enrollmentId:id,userUid:uid,courseId:course.id,courseTitle:course.title,audience:course.audience,status:'in-progress',currentLesson:0,attempts:0,score:null,enrolledAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});}
export async function completeCourse(db,uid,course,answers){const score=Math.round((course.questions.reduce((n,q,i)=>n+(Number(answers[i])===q.answer?1:0),0)/Math.max(course.questions.length,1))*100);const enrollmentRef=doc(db,'academyEnrollments',`${uid}_${course.id}`);await runTransaction(db,async tx=>{const snap=await tx.get(enrollmentRef);const attempts=(snap.exists()?snap.data().attempts||0:0)+1;const passed=score>=Number(course.passingScore||70);tx.set(enrollmentRef,{enrollmentId:`${uid}_${course.id}`,userUid:uid,courseId:course.id,courseTitle:course.title,audience:course.audience,status:passed?'completed':'in-progress',currentLesson:course.lessons?.length||0,attempts,score,completedAt:passed?serverTimestamp():null,updatedAt:serverTimestamp()},{merge:true});if(passed){const certId=`CERT-${crypto.randomUUID().slice(0,8).toUpperCase()}`;tx.set(doc(db,'academyCertificates',certId),{certificateId:certId,userUid:uid,courseId:course.id,courseTitle:course.title,score,issuedAt:serverTimestamp(),status:'active',xpAwarded:Number(course.xp||0),immutable:true});const profileRef=doc(db,'academyProfiles',uid);const profile=await tx.get(profileRef);tx.set(profileRef,{uid,xp:(profile.exists()?Number(profile.data().xp||0):0)+Number(course.xp||0),level:Math.max(1,Math.floor(((profile.exists()?Number(profile.data().xp||0):0)+Number(course.xp||0))/500)+1),completedCourses:(profile.exists()?Number(profile.data().completedCourses||0):0)+1,updatedAt:serverTimestamp()},{merge:true});}});return{score,passed};}
export async function createCourse(db,uid,data){if(data.title.trim().length<3||data.description.trim().length<10)throw new Error('Enter a complete title and description.');const lessons=data.lessonsText.split('\n').map(x=>x.trim()).filter(Boolean).map((body,i)=>({title:`Lesson ${i+1}`,body}));const questions=data.questionsText.split('\n').map(x=>x.trim()).filter(Boolean).map((line,i)=>{const parts=line.split('|').map(x=>x.trim());return{prompt:parts[0]||`Question ${i+1}`,options:[parts[1]||'True',parts[2]||'False'],answer:Number(parts[3]||0)}});await addDoc(collection(db,'academyCourses'),{courseId:`CRS-${crypto.randomUUID().slice(0,8).toUpperCase()}`,title:data.title.trim(),description:data.description.trim(),audience:data.audience,category:data.category.trim()||'General',passingScore:Number(data.passingScore||70),xp:Number(data.xp||100),required:Boolean(data.required),lessons,questions,active:true,createdBy:uid,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});}
export async function assignCourse(db,uid,data){if(!data.staffUid||!data.courseId)throw new Error('Choose a staff member and course.');await addDoc(collection(db,'trainingAssignments'),{assignmentId:`TRN-${crypto.randomUUID().slice(0,8).toUpperCase()}`,staffUid:data.staffUid,courseId:data.courseId,type:data.type||'required-training',status:'assigned',required:true,dueDate:data.dueDate||null,assignedBy:uid,assignedAt:serverTimestamp()});}
