import{addDoc,collection,doc,getDoc,getDocs,query,runTransaction,serverTimestamp,setDoc,updateDoc,where}from'firebase/firestore';

const docs=s=>s.docs.map(i=>({id:i.id,...i.data()}));
const code=p=>`${p}-${crypto.randomUUID().slice(0,8).toUpperCase()}`;

export const BUSINESS_LEVELS=['startup','developing','established','regional','national','institutional-partner'];
export const PROPERTY_TYPES=['apartment','house','luxury-residence','farm','retail-store','office','warehouse','restaurant','hotel','factory','commercial-complex'];
export const POLICY_STATUSES=['active','suspended','lapsed','expired','claim-restricted','cancelled'];
export const INVESTMENT_PRODUCTS=[['afg-bond','AFG Institutional Bond','low'],['savings-bond','Savings Bond','low'],['index-fund','Apex Index Fund','moderate'],['growth-fund','Apex Growth Fund','high'],['property-fund','Property Fund','moderate'],['business-fund','Business Enterprise Fund','high']].map(([id,name,risk])=>({id,name,risk}));
export const INSURANCE_PRODUCTS=[['property','Property Coverage'],['business','Business Coverage'],['loan','Loan Protection'],['income','Income Protection'],['vehicle','Vehicle Coverage']].map(([id,name])=>({id,name}));
export const DEFAULT_ECONOMY_PRICING={businessBasePrice:500,propertyBasePrice:5000,insuranceSetupFee:100,insurancePremiumRate:.02};

const pricing=(s={})=>({businessBasePrice:Math.max(0,Number(s.businessBasePrice??500)),propertyBasePrice:Math.max(1,Number(s.propertyBasePrice??5000)),insuranceSetupFee:Math.max(0,Number(s.insuranceSetupFee??100)),insurancePremiumRate:Math.max(0,Number(s.insurancePremiumRate??.02))});
export function policyCost(settings,coverage){const p=pricing(settings),premium=Math.max(1,Math.round(Number(coverage||0)*p.insurancePremiumRate*100)/100);return{setupFee:p.insuranceSetupFee,premium,total:p.insuranceSetupFee+premium}}
export function eligibleInsuranceAssets(data,type){if(!data)return[];if(type==='property')return data.properties.map(x=>({id:x.id,permanentId:x.propertyId,name:x.name,type:'property'}));if(type==='business')return data.businesses.map(x=>({id:x.id,permanentId:x.businessId,name:x.name,type:'business'}));if(type==='loan')return data.loans.map(x=>({id:x.id,permanentId:x.loanId,name:x.productName||x.loanType||'AFG Loan',type:'loan'}));if(type==='income')return[{id:data.user.uid,permanentId:data.user.customerId,name:data.user.displayName||data.user.username||'Customer income',type:'customer'}];return[]}

function deriveInvestment(investment,operations){
 const basePrincipal=Number(investment._basePrincipal??investment.principal??0),baseCurrentValue=Number(investment._baseCurrentValue??investment.currentValue??0);
 const related=operations.filter(x=>x.investmentDocId===investment.id&&['investment-add','investment-withdraw','investment-close'].includes(x.type));
 const closed=related.some(x=>x.type==='investment-close');
 const principalDelta=related.reduce((sum,x)=>sum+Number(x.principalDelta||0),0),valueDelta=related.reduce((sum,x)=>sum+Number(x.valueDelta||0),0);
 const principal=Math.max(0,basePrincipal+principalDelta),currentValue=Math.max(0,baseCurrentValue+valueDelta);
 return{...investment,_basePrincipal:basePrincipal,_baseCurrentValue:baseCurrentValue,principal,currentValue,totalReturn:currentValue-principal,status:closed?'closed':investment.status,closed};
}

export async function loadEconomy(db,uid){
 const[userSnap,bootstrap,permissionSnap,settingsSnap]=await Promise.all([getDoc(doc(db,'users',uid)),getDoc(doc(db,'system','bootstrap')),getDoc(doc(db,'staffPermissions',uid)),getDoc(doc(db,'economicSettings','current'))]);
 if(!userSnap.exists())throw new Error('Customer identity not found.');
 const isOwner=bootstrap.exists()&&bootstrap.data().ownerUid===uid,grants=permissionSnap.exists()?permissionSnap.data().permissions||[]:[],mayManage=isOwner||grants.some(x=>['business.manage','property.manage','investments.manage','insurance.manage','owner.override_all'].includes(x)),mayInsurance=isOwner||grants.includes('insurance.manage')||grants.includes('owner.override_all');
 const[businesses,properties,investments,policies,claims,accounts,loans,incidents,operations,investmentOperations]=await Promise.all([
  getDocs(query(collection(db,'businesses'),where('ownerUid','==',uid))),getDocs(query(collection(db,'properties'),where('ownerUid','==',uid))),getDocs(query(collection(db,'investments'),where('ownerUid','==',uid))),getDocs(query(collection(db,'insurancePolicies'),where('ownerUid','==',uid))),getDocs(query(collection(db,'insuranceClaims'),where('ownerUid','==',uid))),getDocs(query(collection(db,'accounts'),where('ownerUid','==',uid))),getDocs(query(collection(db,'loans'),where('ownerUid','==',uid))),getDocs(query(collection(db,'institutionEvents'),where('propertyOwnerUid','==',uid))),getDocs(query(collection(db,'bankingOperations'),where('ownerUid','==',uid))),getDocs(query(collection(db,'investmentOperations'),where('ownerUid','==',uid)))
 ]);
 let managedClaims=[],managedPolicies=[];if(mayInsurance){try{managedClaims=docs(await getDocs(collection(db,'insuranceClaims')))}catch{}try{managedPolicies=docs(await getDocs(collection(db,'insurancePolicies')))}catch{}}
 const ownOps=docs(operations),invOps=docs(investmentOperations),disposedBusinesses=new Set(ownOps.filter(x=>x.type==='business_shutdown').map(x=>x.targetDocId)),disposedProperties=new Set(ownOps.filter(x=>x.type==='property_sale').map(x=>x.targetDocId));
 const activeBusinesses=docs(businesses).filter(x=>!disposedBusinesses.has(x.id)),activeProperties=docs(properties).filter(x=>!disposedProperties.has(x.id)),activeInvestments=docs(investments).map(x=>deriveInvestment(x,invOps)).filter(x=>!x.closed);
 const ownPolicies=docs(policies),paidClaimIds=new Set(ownOps.filter(x=>x.type==='insurance_claim_payout').map(x=>x.claimId)),disposedAssetIds=new Set([...disposedBusinesses,...disposedProperties]);
 const visiblePolicies=ownPolicies.map(p=>disposedAssetIds.has(p.insuredAssetId)?{...p,status:'cancelled',lifecycleReason:'Insured asset was sold or shut down.'}:p).filter(x=>x.status!=='cancelled');
 const ownClaims=docs(claims).map(c=>paidClaimIds.has(c.claimId)?{...c,status:'paid',payoutStatus:'paid'}:c);
 return{user:{uid,...userSnap.data()},businesses:activeBusinesses,properties:activeProperties,investments:activeInvestments,policies:visiblePolicies,policyHistory:ownPolicies,claims:ownClaims,accounts:docs(accounts),loans:docs(loans),incidents:docs(incidents).filter(x=>x.eventType==='property-incident'&&x.status!=='cancelled'),operations:ownOps,investmentOperations:invOps,managedClaims,managedPolicies,economy:{...DEFAULT_ECONOMY_PRICING,...(settingsSnap.exists()?settingsSnap.data():{})},access:{isOwner,mayManage,mayInsurance,permissions:grants}};
}

async function debitForEconomy(tx,db,user,accountId,amount,type,description,targetId){const accountRef=doc(db,'accounts',accountId),accountSnap=await tx.get(accountRef);if(!accountSnap.exists()||accountSnap.data().ownerUid!==user.uid)throw new Error('Choose one of your AFG accounts.');const available=Number(accountSnap.data().availableBalance||0);if(available<amount)throw new Error(`Insufficient available funds. This action costs ${amount.toLocaleString()} fictional currency.`);const operationId=code('ECO');tx.update(accountRef,{balance:Number(accountSnap.data().balance||0)-amount,availableBalance:available-amount,lastOperationId:operationId,updatedAt:serverTimestamp()});tx.set(doc(db,'bankingOperations',operationId),{operationId,ownerUid:user.uid,customerId:user.customerId,accountId,targetId,type,amount,status:'completed',immutable:true,createdAt:serverTimestamp()});tx.set(doc(collection(db,'transactions')),{transactionId:code('TXN'),operationId,ownerUid:user.uid,customerId:user.customerId,accountId,type,direction:'debit',amount,description,status:'completed',createdAt:serverTimestamp()});return operationId}
async function creditEconomyExit(tx,db,user,accountRef,accountSnap,operationRef,amount,type,description,targetDocId,targetPermanentId){if(!accountSnap.exists()||accountSnap.data().ownerUid!==user.uid)throw new Error('Choose one of your AFG accounts.');tx.update(accountRef,{balance:Number(accountSnap.data().balance||0)+amount,availableBalance:Number(accountSnap.data().availableBalance||0)+amount,lastOperationId:operationRef.id,updatedAt:serverTimestamp()});tx.set(operationRef,{operationId:operationRef.id,ownerUid:user.uid,customerId:user.customerId,accountId:accountRef.id,targetDocId,targetPermanentId,type,amount,status:'completed',immutable:true,createdAt:serverTimestamp()});tx.set(doc(collection(db,'transactions')),{transactionId:code('TXN'),operationId:operationRef.id,ownerUid:user.uid,customerId:user.customerId,accountId:accountRef.id,type,direction:'credit',amount,description,status:'completed',createdAt:serverTimestamp()})}

export async function registerBusiness(db,user,data,settings={}){const capital=Number(data.startingCapital||0);if(!data.name?.trim()||data.name.trim().length<3||!data.description?.trim()||data.description.trim().length<20)throw new Error('Enter a business name and complete description.');if(capital<0||capital>100000)throw new Error('Starting capital must be between 0 and 100,000 fictional currency.');if(!data.accountId)throw new Error('Choose a funding account.');const fee=pricing(settings).businessBasePrice,total=fee+capital,businessRef=doc(collection(db,'businesses')),businessId=code('BUS');await runTransaction(db,async tx=>{await debitForEconomy(tx,db,user,data.accountId,total,'business_setup',`Business setup: ${data.name.trim()}`,businessId);tx.set(businessRef,{businessId,ownerUid:user.uid,customerId:user.customerId,name:data.name.trim(),industry:String(data.industry||'general').trim(),description:data.description.trim(),homeBranchId:data.homeBranchId||'capital',ownershipType:data.ownershipType||'sole-owner',level:'startup',status:'active',reputation:500,revenue:0,expenses:fee,cashReserves:capital,employeeCount:0,setupFeePaid:fee,fundingAccountId:data.accountId,createdAt:serverTimestamp(),updatedAt:serverTimestamp()})});return businessId}
export async function addBusinessActivity(db,uid,business,kind,amount,memo){const value=Number(amount);if(!value||value<=0||value>100000)throw new Error('Enter a positive amount no greater than 100,000.');const ref=doc(db,'businesses',business.id);await runTransaction(db,async tx=>{const snap=await tx.get(ref);if(!snap.exists()||snap.data().ownerUid!==uid)throw new Error('Business not found.');const c=snap.data(),revenue=Number(c.revenue||0)+(kind==='revenue'?value:0),expenses=Number(c.expenses||0)+(kind==='expense'?value:0),cashReserves=Number(c.cashReserves||0)+(kind==='revenue'?value:-value);if(cashReserves<0)throw new Error('Business reserves are insufficient.');tx.update(ref,{revenue,expenses,cashReserves,updatedAt:serverTimestamp()});tx.set(doc(collection(db,'businessTransactions')),{transactionId:code('BTX'),businessId:c.businessId,businessDocId:business.id,ownerUid:uid,type:kind,amount:value,memo:String(memo||'').trim(),immutable:true,createdAt:serverTimestamp()})})}
export async function shutdownBusiness(db,user,business,accountId){if(!accountId)throw new Error('Choose an account for the shutdown payout.');const businessRef=doc(db,'businesses',business.id),accountRef=doc(db,'accounts',accountId),operationRef=doc(db,'bankingOperations',`BUS-SHUT-${business.id}`);let payout=0;await runTransaction(db,async tx=>{const[businessSnap,accountSnap]=await Promise.all([tx.get(businessRef),tx.get(accountRef)]);if(!businessSnap.exists()||businessSnap.data().ownerUid!==user.uid)throw new Error('Business not found.');const current=businessSnap.data(),companyValue=Math.max(0,Number(current.cashReserves||0));payout=Math.round(companyValue*.45*100)/100;if(payout<=0)throw new Error('This business currently has no positive shutdown value.');await creditEconomyExit(tx,db,user,accountRef,accountSnap,operationRef,payout,'business_shutdown',`Business shutdown payout: ${current.name||business.name}`,business.id,current.businessId||business.businessId);tx.set(doc(collection(db,'businessTransactions')),{transactionId:code('BTX'),businessId:current.businessId||business.businessId,businessDocId:business.id,ownerUid:user.uid,type:'shutdown',amount:payout,memo:`Business shut down for 45% of current company value (${companyValue}).`,immutable:true,createdAt:serverTimestamp()})});return payout}

export async function acquireProperty(db,user,data,settings={}){if(!data.propertyType)throw new Error('Choose a property type.');if(!data.accountId)throw new Error('Choose a funding account.');const basePrice=pricing(settings).propertyBasePrice,price=Number(data.purchasePrice||basePrice);if(!Number.isFinite(price)||price<basePrice||price>100000000)throw new Error(`Property price must be at least the current base price of ${basePrice.toLocaleString()}.`);const propertyRef=doc(collection(db,'properties')),propertyId=code('PROP');await runTransaction(db,async tx=>{await debitForEconomy(tx,db,user,data.accountId,price,'property_purchase',`Property purchase: ${data.name||data.propertyType}`,propertyId);tx.set(propertyRef,{propertyId,ownerUid:user.uid,customerId:user.customerId,businessId:data.businessId||null,name:String(data.name||'').trim()||'Unnamed Property',propertyType:data.propertyType,status:'owned',purchasePrice:price,currentValue:price,mortgageLoanId:data.mortgageLoanId||null,condition:'good',rentalIncome:Number(data.rentalIncome||0),maintenanceCost:Number(data.maintenanceCost||0),insured:false,fundingAccountId:data.accountId,createdAt:serverTimestamp(),updatedAt:serverTimestamp()})});return propertyId}
export async function sellProperty(db,user,property,accountId){if(!accountId)throw new Error('Choose an account for the property sale payout.');const propertyRef=doc(db,'properties',property.id),accountRef=doc(db,'accounts',accountId),operationRef=doc(db,'bankingOperations',`PROP-SALE-${property.id}`);let payout=0;await runTransaction(db,async tx=>{const[propertySnap,accountSnap]=await Promise.all([tx.get(propertyRef),tx.get(accountRef)]);if(!propertySnap.exists()||propertySnap.data().ownerUid!==user.uid)throw new Error('Property not found.');const current=propertySnap.data(),currentValue=Math.max(0,Number(current.currentValue??current.purchasePrice??0));payout=Math.round(currentValue*.70*100)/100;if(payout<=0)throw new Error('This property currently has no positive sale value.');await creditEconomyExit(tx,db,user,accountRef,accountSnap,operationRef,payout,'property_sale',`Property sale payout: ${current.name||property.name}`,property.id,current.propertyId||property.propertyId)});return payout}

export async function purchaseInvestment(db,user,data){const amount=Number(data.amount);if(!amount||amount<=0||amount>1000000)throw new Error('Enter an investment amount between 1 and 1,000,000.');const accountRef=doc(db,'accounts',data.accountId),investmentRef=doc(collection(db,'investments')),operationId=code('IOP'),product=INVESTMENT_PRODUCTS.find(x=>x.id===data.productId);if(!product)throw new Error('Select a valid investment product.');await runTransaction(db,async tx=>{const account=await tx.get(accountRef);if(!account.exists()||account.data().ownerUid!==user.uid||Number(account.data().availableBalance||0)<amount)throw new Error('Selected account has insufficient available funds.');tx.update(accountRef,{balance:Number(account.data().balance||0)-amount,availableBalance:Number(account.data().availableBalance||0)-amount,lastOperationId:operationId,updatedAt:serverTimestamp()});tx.set(investmentRef,{investmentId:code('INV'),ownerUid:user.uid,customerId:user.customerId,productId:product.id,productName:product.name,risk:product.risk,principal:amount,currentValue:amount,totalReturn:0,status:'active',purchasedFromAccountId:data.accountId,operationId,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});tx.set(doc(db,'investmentOperations',operationId),{operationId,investmentDocId:investmentRef.id,ownerUid:user.uid,customerId:user.customerId,accountId:data.accountId,type:'investment-purchase',amount,status:'completed',immutable:true,createdAt:serverTimestamp()});tx.set(doc(collection(db,'transactions')),{transactionId:code('TXN'),operationId,ownerUid:user.uid,customerId:user.customerId,accountId:data.accountId,type:'investment_purchase',direction:'debit',amount,status:'completed',description:`Purchased ${product.name}`,createdAt:serverTimestamp()})})}
export async function adjustInvestment(db,user,investment,accountId,mode,rawAmount){
 const amount=Number(rawAmount);if(!['add','withdraw'].includes(mode))throw new Error('Choose add funds or withdraw.');if(!accountId)throw new Error('Choose an AFG account.');if(!Number.isFinite(amount)||amount<=0||amount>1000000)throw new Error('Enter an amount between 1 and 1,000,000.');
 const operations=docs(await getDocs(query(collection(db,'investmentOperations'),where('ownerUid','==',user.uid)))),base={...investment,principal:investment._basePrincipal??investment.principal,currentValue:investment._baseCurrentValue??investment.currentValue},current=deriveInvestment(base,operations);
 if(current.closed)throw new Error('This investment is already closed.');if(mode==='withdraw'&&amount>current.currentValue)throw new Error('You cannot withdraw more than the investment current value.');
 const investmentRef=doc(db,'investments',investment.id),accountRef=doc(db,'accounts',accountId),operationRef=doc(db,'investmentOperations',code('IOP'));
 await runTransaction(db,async tx=>{const[investmentSnap,accountSnap]=await Promise.all([tx.get(investmentRef),tx.get(accountRef)]);if(!investmentSnap.exists()||investmentSnap.data().ownerUid!==user.uid)throw new Error('Investment not found.');if(!accountSnap.exists()||accountSnap.data().ownerUid!==user.uid)throw new Error('Choose one of your AFG accounts.');if(mode==='add'&&Number(accountSnap.data().availableBalance||0)<amount)throw new Error('Selected account has insufficient available funds.');const fullClose=mode==='withdraw'&&amount>=current.currentValue,principalReduction=mode==='withdraw'?(current.currentValue>0?Math.min(current.principal,current.principal*(amount/current.currentValue)):0):0,principalDelta=mode==='add'?amount:-principalReduction,valueDelta=mode==='add'?amount:-amount,type=fullClose?'investment-close':mode==='add'?'investment-add':'investment-withdraw';const balance=Number(accountSnap.data().balance||0)+(mode==='add'?-amount:amount),available=Number(accountSnap.data().availableBalance||0)+(mode==='add'?-amount:amount);tx.update(accountRef,{balance,availableBalance:available,lastOperationId:operationRef.id,updatedAt:serverTimestamp()});tx.set(operationRef,{operationId:operationRef.id,investmentDocId:investment.id,investmentId:investment.investmentId,ownerUid:user.uid,customerId:user.customerId,accountId,type,amount,principalDelta,valueDelta,status:'completed',immutable:true,createdAt:serverTimestamp()});tx.set(doc(collection(db,'transactions')),{transactionId:code('TXN'),operationId:operationRef.id,ownerUid:user.uid,customerId:user.customerId,accountId,type,direction:mode==='add'?'debit':'credit',amount,status:'completed',description:`${mode==='add'?'Added to':'Withdrew from'} ${investment.productName}`,createdAt:serverTimestamp()})});return{closed:mode==='withdraw'&&amount>=current.currentValue};
}

export async function createInsurancePolicy(db,user,data,economySettings={}){const coverage=Number(data.coverage),deductible=Number(data.deductible||0);if(!data.productType||!coverage||coverage<=0)throw new Error('Choose a policy type and valid coverage amount.');if(!data.accountId)throw new Error('Choose a funding account.');if(!data.assetId||!data.assetType)throw new Error('Choose an eligible asset to insure.');const costs=policyCost(economySettings,coverage),policyRef=doc(collection(db,'insurancePolicies')),policyId=code('POL');await runTransaction(db,async tx=>{await debitForEconomy(tx,db,user,data.accountId,costs.total,'insurance_policy_opening',`Insurance opening cost: ${policyId}`,policyId);tx.set(policyRef,{policyId,ownerUid:user.uid,customerId:user.customerId,productType:data.productType,productName:INSURANCE_PRODUCTS.find(x=>x.id===data.productType)?.name||data.productType,insuredAssetType:data.assetType,insuredAssetId:data.assetId,insuredAssetPermanentId:data.assetPermanentId||null,insuredAssetName:data.assetName||'Insured asset',premium:costs.premium,setupFee:costs.setupFee,coverageLimit:coverage,deductible,status:'active',lifecycleReason:'Policy created and initial premium paid.',fundingAccountId:data.accountId,effectiveAt:serverTimestamp(),createdAt:serverTimestamp(),updatedAt:serverTimestamp()})});return policyId}
export async function managePolicyLifecycle(db,actor,policy,status,reason){if(!actor?.mayInsurance)throw new Error('Insurance officer permission is required.');if(!POLICY_STATUSES.includes(status))throw new Error('Choose a valid policy status.');const clean=String(reason||'').trim();if(clean.length<10)throw new Error('Enter a lifecycle reason of at least 10 characters.');const ref=doc(db,'insurancePolicies',policy.id),auditRef=doc(collection(db,'auditLogs'));await runTransaction(db,async tx=>{const snap=await tx.get(ref);if(!snap.exists())throw new Error('Policy no longer exists.');const c=snap.data();tx.update(ref,{status,lifecycleReason:clean,lifecycleUpdatedBy:actor.uid,lifecycleUpdatedAt:serverTimestamp(),cancelledAt:status==='cancelled'?serverTimestamp():c.cancelledAt||null,updatedAt:serverTimestamp()});tx.set(auditRef,{auditId:auditRef.id,actorUid:actor.uid,actorType:actor.isOwner?'owner':'staff',action:`insurance.policy.${status}`,targetType:'insurancePolicy',targetId:c.policyId,reason:clean,immutable:true,createdAt:serverTimestamp()})})}
export async function submitClaim(db,user,data){if(!data.description?.trim()||data.description.trim().length<25)throw new Error('Provide a complete fictional claim description.');const policy=await getDoc(doc(db,'insurancePolicies',data.policyDocId));if(!policy.exists()||policy.data().ownerUid!==user.uid)throw new Error('Policy not found.');if(policy.data().status!=='active')throw new Error(`Claims cannot be submitted while this policy is ${policy.data().status}.`);const disposed=docs(await getDocs(query(collection(db,'bankingOperations'),where('ownerUid','==',user.uid)))).some(x=>['business_shutdown','property_sale'].includes(x.type)&&x.targetDocId===policy.data().insuredAssetId);if(disposed)throw new Error('Claims cannot be submitted for an asset that has been sold or shut down.');const amount=Number(data.amount||0);if(amount<=0||amount>Number(policy.data().coverageLimit||0))throw new Error('Claim amount must be positive and within the policy limit.');if(data.incidentEventId){const incident=await getDoc(doc(db,'institutionEvents',data.incidentEventId));if(!incident.exists()||incident.data().propertyOwnerUid!==user.uid||incident.data().status==='cancelled'||incident.data().claimEligible===false)throw new Error('Selected property incident is unavailable for claims.');}await addDoc(collection(db,'insuranceClaims'),{claimId:code('CLM'),policyDocId:data.policyDocId,policyId:policy.data().policyId,ownerUid:user.uid,customerId:user.customerId,insuredAssetId:policy.data().insuredAssetId,insuredAssetName:policy.data().insuredAssetName||null,requestedAmount:amount,incidentType:String(data.incidentType||'').trim(),incidentEventId:data.incidentEventId||null,description:data.description.trim(),status:'submitted',assignedReviewerUid:null,decision:null,payoutStatus:'not-approved',uploadsAllowed:false,createdAt:serverTimestamp(),updatedAt:serverTimestamp()})}
export async function decideClaim(db,actor,claim,decision){if(!actor?.mayInsurance)throw new Error('Insurance officer permission is required.');if(!decision.reason?.trim()||decision.reason.trim().length<10)throw new Error('Enter a decision reason.');const outcome=decision.outcome;if(!['approved','denied'].includes(outcome))throw new Error('Choose approve or deny.');const approvedAmount=outcome==='approved'?Number(decision.approvedAmount||0):0;if(outcome==='approved'&&(approvedAmount<=0||approvedAmount>Number(claim.requestedAmount||0)))throw new Error('Approved amount must be greater than zero and cannot exceed the requested amount.');await updateDoc(doc(db,'insuranceClaims',claim.id),{status:outcome,assignedReviewerUid:actor.uid,decision:{outcome,approvedAmount,reason:decision.reason.trim(),decidedBy:actor.uid,ownerOverride:Boolean(actor.isOwner),decidedAt:new Date().toISOString()},payoutStatus:outcome==='approved'?'available':'not-approved',updatedAt:serverTimestamp()});await addDoc(collection(db,'auditLogs'),{actorUid:actor.uid,actorType:actor.isOwner?'owner':'staff',action:'insurance.claim.decided',targetType:'insuranceClaim',targetId:claim.claimId,reason:decision.reason.trim(),immutable:true,createdAt:serverTimestamp()})}
export async function collectClaimPayout(db,user,claim,accountId){if(claim.ownerUid!==user.uid||claim.status!=='approved'||claim.payoutStatus!=='available')throw new Error('This claim does not have an available payout.');const policyRef=doc(db,'insurancePolicies',claim.policyDocId),accountRef=doc(db,'accounts',accountId),operationRef=doc(db,'bankingOperations',`CLM-${claim.id}`);await runTransaction(db,async tx=>{const[policySnap,accountSnap]=await Promise.all([tx.get(policyRef),tx.get(accountRef)]);if(!accountSnap.exists()||accountSnap.data().ownerUid!==user.uid)throw new Error('Choose one of your AFG accounts.');const approved=Number(claim.decision?.approvedAmount||0),deductible=Number(policySnap.exists()?policySnap.data().deductible||0:0),payout=Math.max(0,approved-deductible);if(payout<=0)throw new Error('The approved amount does not exceed the policy deductible.');tx.update(accountRef,{balance:Number(accountSnap.data().balance||0)+payout,availableBalance:Number(accountSnap.data().availableBalance||0)+payout,lastOperationId:operationRef.id,updatedAt:serverTimestamp()});tx.set(operationRef,{operationId:operationRef.id,ownerUid:user.uid,customerId:user.customerId,accountId,claimId:claim.claimId,type:'insurance_claim_payout',amount:payout,status:'completed',immutable:true,createdAt:serverTimestamp()});tx.set(doc(collection(db,'transactions')),{transactionId:code('TXN'),operationId:operationRef.id,ownerUid:user.uid,customerId:user.customerId,accountId,type:'insurance_claim_payout',direction:'credit',amount:payout,description:`Insurance payout for ${claim.claimId}`,status:'completed',createdAt:serverTimestamp()})})}
