import React,{useEffect,useMemo,useState}from'react';
import{getApp,getApps,initializeApp}from'firebase/app';
import{getAuth,onAuthStateChanged,signOut}from'firebase/auth';
import{getFirestore}from'firebase/firestore';
import{ArrowLeft,CheckCircle2,Landmark,LogOut,RefreshCw,Search,ShieldCheck,TrendingUp,UserCog,Users,XCircle}from'lucide-react';
import{applyStaffManagementAction,denyPromotionRequest,loadStaffManagement}from'./staffManagementService.js';
import'../styles.css';import'../stabilization.css';import'./staffManagement.css';
const config={apiKey:'AIzaSyCG7LQR2vM2r68Y414jToA1_CDmUE_Ncdw',authDomain:'afg-game.firebaseapp.com',projectId:'afg-game',storageBucket:'afg-game.firebasestorage.app',messagingSenderId:'779966850290',appId:'1:779966850290:web:24f48af23a2e6cae2d9c6b'};
const app=getApps().length?getApp():initializeApp(config),auth=getAuth(app),db=getFirestore(app);
const label=v=>(v||'').split('-').map(x=>x?x[0].toUpperCase()+x.slice(1):'').join(' ');
export default function StaffManagementPage(){
 const[user,setUser]=useState(null),[data,setData]=useState(null),[selected,setSelected]=useState(null),[search,setSearch]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[form,setForm]=useState({rankId:'',departmentId:'',branchId:'',position:'',reason:''});
 async function refresh(uid=user?.uid){if(!uid)return;const next=await loadStaffManagement(db,uid);setData(next);setSelected(s=>next.staff.find(x=>x.uid===s?.uid)||null)}
 useEffect(()=>onAuthStateChanged(auth,async u=>{if(!u){location.href='/signin';return}setUser(u);try{await refresh(u.uid)}catch(e){setError(e.message)}}),[]);
 const visible=useMemo(()=>data?.staff.filter(s=>`${s.displayName} ${s.staffId} ${s.rankName} ${s.departmentName||s.departmentId||''}`.toLowerCase().includes(search.toLowerCase()))||[],[data,search]);
 function choose(s){setSelected(s);setForm({rankId:s.pendingPromotionRequest?.requestedRankId||s.rankId||data.ranks.find(r=>r.name===s.rankName)?.id||'',departmentId:s.departmentId||'',branchId:s.branchId||'',position:s.position||'',reason:''});}
 async function save(){if(!selected)return;setBusy(true);setError('');setSuccess('');try{const action=await applyStaffManagementAction(db,{uid:user.uid,staffId:data.actor?.staffId},data,selected,form);setSuccess(`${label(action)} completed for ${selected.displayName}.`);await refresh()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function deny(){if(!selected?.pendingPromotionRequest)return;setBusy(true);setError('');setSuccess('');try{await denyPromotionRequest(db,{uid:user.uid,staffId:data.actor?.staffId},data,selected,form.reason);setSuccess(`Promotion request denied for ${selected.displayName}.`);await refresh()}catch(e){setError(e.message)}finally{setBusy(false)}}
 if(!user||!data)return <main className="sm-loading"><Landmark/><strong>AFG Staff Management</strong><span>Loading management authority…</span></main>;
 if(!data.allowed)return <main className="sm-loading"><ShieldCheck/><strong>Manager access required</strong><span>This page is available to Managers and above.</span><a href="/staff">Return to Staff Workspace</a></main>;
 return <div className="sm-shell"><aside><a href="/"><Landmark/> AFG</a><a href="/staff"><ArrowLeft/> Staff Workspace</a><a className="active" href="/staff-management"><UserCog/> Staff Management</a><a href="/career-center"><Users/> Career Center</a><button onClick={()=>signOut(auth).then(()=>location.href='/')}><LogOut/> Sign out</button></aside><main><header><div><small>MANAGEMENT OPERATIONS</small><h1>Staff Management</h1><p>Promotion readiness, rank changes, transfers, and career decisions in one workspace.</p></div><button onClick={()=>refresh()}><RefreshCw/> Refresh</button></header>{error&&<div className="form-alert">{error}</div>}{success&&<div className="sm-success">{success}</div>}
 <section className="sm-summary"><article><TrendingUp/><span><small>Pending promotions</small><strong>{data.promotionRequests.length}</strong></span></article><article><CheckCircle2/><span><small>Promotion-ready staff</small><strong>{data.staff.filter(x=>x.readiness?.ready).length}</strong></span></article><article><Users/><span><small>Manageable staff</small><strong>{data.staff.filter(x=>data.isOwner||x.rankScore<data.actorScore).length}</strong></span></article></section>
 <div className="sm-layout"><section className="sm-directory"><div className="sm-search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search staff"/></div>{visible.map(s=><button key={s.uid} className={selected?.uid===s.uid?'selected':''} onClick={()=>choose(s)}><span><strong>{s.displayName}</strong><small>{s.staffId} · {s.rankName||'Unranked'}</small>{s.pendingPromotionRequest&&<em>Promotion requested</em>}</span>{s.readiness?.ready?<CheckCircle2/>:s.protectedOwner?<ShieldCheck/>:null}</button>)}</section>
 <section className="sm-editor">{selected?<><div className="sm-head"><div><small>{selected.staffId}</small><h2>{selected.displayName}</h2><p>{selected.rankName} · {selected.position}</p></div>{selected.readiness?.ready&&<span className="ready-chip">Promotion ready</span>}</div>
 <section className="promotion-readiness"><h3>Promotion readiness</h3><div className="readiness-grid"><span className={selected.readiness?.trainingComplete?'ok':'wait'}>{selected.readiness?.trainingComplete?<CheckCircle2/>:<XCircle/>} Training <b>{selected.readiness?.completedTraining}/{selected.readiness?.requiredTraining}</b></span><span className={selected.readiness?.probationComplete?'ok':'wait'}>{selected.readiness?.probationComplete?<CheckCircle2/>:<XCircle/>} Probation</span><span className={selected.readiness?.performanceReady?'ok':'wait'}>{selected.readiness?.performanceReady?<CheckCircle2/>:<XCircle/>} Performance <b>{selected.readiness?.latestScore||0}</b></span><span className={selected.readiness?.disciplineClear?'ok':'wait'}>{selected.readiness?.disciplineClear?<CheckCircle2/>:<XCircle/>} Discipline clear</span></div>{selected.pendingPromotionRequest&&<div className="promotion-request"><strong>Pending promotion request</strong><p>{selected.pendingPromotionRequest.reason}</p><small>Requested rank: {data.ranks.find(r=>r.id===selected.pendingPromotionRequest.requestedRankId)?.name||selected.pendingPromotionRequest.requestedRankId||'Not specified'}</small></div>}</section>
 {selected.protectedOwner?<div className="sm-protected"><ShieldCheck/><h3>Protected Owner account</h3><p>This staff profile cannot be modified.</p></div>:selected.uid===user.uid?<div className="sm-protected"><ShieldCheck/><h3>Self-management blocked</h3><p>You cannot promote, demote, or transfer yourself.</p></div>:<div className="sm-form"><label>Rank<select value={form.rankId} onChange={e=>setForm({...form,rankId:e.target.value})}><option value="">Choose rank</option>{data.ranks.filter(r=>data.isOwner||r.score<data.actorScore).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>Position<input value={form.position} onChange={e=>setForm({...form,position:e.target.value})}/></label><label>Department<select value={form.departmentId} onChange={e=>setForm({...form,departmentId:e.target.value})}><option value="">Keep current</option>{data.departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Branch<select value={form.branchId} onChange={e=>setForm({...form,branchId:e.target.value})}><option value="">Keep current</option>{data.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Written reason<textarea value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})} placeholder="Explain the promotion, demotion, transfer, or promotion decision."/></label><div className="sm-actions"><button disabled={busy||!form.rankId} onClick={save}>{busy?'Saving…':selected.pendingPromotionRequest?'Approve / apply promotion':'Apply staff action'}</button>{selected.pendingPromotionRequest&&<button className="danger" disabled={busy} onClick={deny}>Deny promotion request</button>}</div></div>}</>:<div className="sm-empty"><UserCog/><h2>Select a staff member</h2><p>Choose someone from the directory to manage their career assignment.</p></div>}</section></div></main></div>;
}
