import{addDoc,collection,doc,getDoc,getDocs,query,runTransaction,serverTimestamp,updateDoc,where}from'firebase/firestore';

export const REVIEW_CATEGORIES=['activity','accuracy','communication','compliance','customerService','teamwork','departmentKnowledge','leadership','trainingCompletion'];
export const REQUEST_TYPES=[['leave','Leave request'],['inactivity','Temporary inactivity'],['branch-transfer','Branch transfer'],['department-transfer','Department transfer'],['promotion','Promotion request'],['resignation','Resignation notice'],['return-from-leave','Return from leave']].map(([id,name])=>({id,name}));
const mapDocs=s=>s.docs.map(d=>({id:d.id,...d.data()}));
const average=v=>{const n=REVIEW_CATEGORIES.map(k=>Number(v?.[k]||0)).filter(x=>x>0);return n.length?Math.round(n.reduce((a,b)=>a+b,0)/n.length*10)/10:0};
const rankLevel=p=>Number(String(p?.rankId||'rank-1').replace(/\D/g,''))||1;

export async function loadCareerCenter(db,uid){
 const[b,u,p,perm,branches,depts,ranks,reviews,requests,training,certificates,staff,loans,apps]=await Promise.all([
  getDoc(doc(db,'system','bootstrap')),getDoc(doc(db,'users',uid)),getDoc(doc(db,'staffProfiles',uid)),getDoc(doc(db,'staffPermissions',uid)),getDocs(collection(db,'branches')),getDocs(collection(db,'departments')),getDocs(collection(db,'ranks')),
  getDocs(query(collection(db,'performanceReviews'),where('staffUid','==',uid))),getDocs(query(collection(db,'careerRequests'),where('staffUid','==',uid))),getDocs(query(collection(db,'trainingAssignments'),where('staffUid','==',uid))),getDocs(query(collection(db,'academyCertificates'),where('holderUid','==',uid))),getDocs(collection(db,'staffProfiles')),getDocs(collection(db,'loans')),getDocs(collection(db,'applications'))
 ]);
 const isOwner=b.exists()&&b.data().ownerUid===uid;const profile=p.exists()?p.data():(isOwner?{uid,staffId:'STF-000001',rankId:'rank-13',rankName:'Founder & Owner',position:'Founder and Owner',departmentId:'executive-office',branchId:'capital',staffStatus:'active',probationStatus:'exempt'}:null);
 const permissions=perm.exists()?perm.data().permissions||[]:[];const manager=isOwner||permissions.some(x=>['staff.manage','performance.manage','branches.manage','owner.override_all'].includes(x));
 let managedReviews=[],managedRequests=[];if(manager){managedReviews=mapDocs(await getDocs(collection(db,'performanceReviews')));managedRequests=mapDocs(await getDocs(collection(db,'careerRequests')))}
 const ownReviews=mapDocs(reviews).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));const completedTraining=mapDocs(training).filter(x=>x.status==='completed').length;const requiredTraining=mapDocs(training).filter(x=>x.required!==false).length;const certs=mapDocs(certificates);const latest=ownReviews[0];const score=latest?.overallScore||average(latest?.scores);
 const readiness={trainingComplete:requiredTraining===0||completedTraining>=requiredTraining,probationComplete:['completed','exempt','inactive'].includes(profile?.probationStatus),performanceReady:score>=3.5,disciplineClear:profile?.disciplinaryStatus!=='active',currentRankLevel:rankLevel(profile)};
 return{access:{allowed:Boolean(profile)||isOwner,isOwner,manager,permissions},user:u.data(),profile,branches:mapDocs(branches),departments:mapDocs(depts),ranks:mapDocs(ranks).sort((a,b)=>(a.level||0)-(b.level||0)),reviews:ownReviews,requests:mapDocs(requests),training:mapDocs(training),certificates:certs,readiness,managedReviews,managedRequests,staff:mapDocs(staff),loans:mapDocs(loans),applications:mapDocs(apps)};
}
export async function submitCareerRequest(db,uid,profile,data){if(!data.type||data.reason.trim().length<15)throw new Error('Choose a request type and provide a complete reason.');await addDoc(collection(db,'careerRequests'),{requestId:`CRQ-${crypto.randomUUID().slice(0,8).toUpperCase()}`,staffUid:uid,staffId:profile.staffId,type:data.type,reason:data.reason.trim(),requestedBranchId:data.branchId||null,requestedDepartmentId:data.departmentId||null,requestedRankId:data.rankId||null,status:'submitted',submittedAt:serverTimestamp(),updatedAt:serverTimestamp()});}
export async function createPerformanceReview(db,actor,data){if(!data.staffUid||data.comments.trim().length<10)throw new Error('Select a staff member and enter review comments.');const overallScore=average(data.scores);await addDoc(collection(db,'performanceReviews'),{reviewId:`PRF-${crypto.randomUUID().slice(0,8).toUpperCase()}`,staffUid:data.staffUid,reviewCycle:data.reviewCycle||'Current cycle',scores:data.scores,overallScore,comments:data.comments.trim(),outcome:data.outcome||'meets-expectations',promotionRecommended:Boolean(data.promotionRecommended),trainingAssigned:data.trainingAssigned.trim(),reviewedBy:actor,createdAt:serverTimestamp(),immutable:true});}
export async function decideCareerRequest(db,actor,id,decision){if((decision.reason||'').trim().length<10)throw new Error('Enter a decision reason.');const ref=doc(db,'careerRequests',id);await runTransaction(db,async tx=>{const snap=await tx.get(ref);if(!snap.exists())throw new Error('Request not found.');const req=snap.data();if(req.status!=='submitted')throw new Error('This request is already decided.');const approved=decision.outcome==='approved';tx.update(ref,{status:approved?'approved':'denied',decisionReason:decision.reason.trim(),decidedBy:actor.uid,decidedAt:serverTimestamp(),ownerOverride:Boolean(decision.ownerOverride),updatedAt:serverTimestamp()});if(approved){const staffRef=doc(db,'staffProfiles',req.staffUid),staffSnap=await tx.get(staffRef);if(!staffSnap.exists())throw new Error('Staff profile not found.');const patch={updatedAt:serverTimestamp()};if(req.type==='leave'||req.type==='inactivity'){patch.staffStatus='leave';patch.leaveStatus='active'}if(req.type==='return-from-leave'){patch.staffStatus='active';patch.leaveStatus='inactive'}if(req.type==='resignation'){patch.staffStatus='inactive';patch.separationStatus='resigned'}if(req.type==='branch-transfer'&&req.requestedBranchId)patch.branchId=req.requestedBranchId;if(req.type==='department-transfer'&&req.requestedDepartmentId)patch.departmentId=req.requestedDepartmentId;if(req.type==='promotion'&&req.requestedRankId){patch.rankId=req.requestedRankId;patch.rankName=decision.rankName||req.requestedRankId;patch.lastPromotionAt=serverTimestamp()}tx.update(staffRef,patch);tx.set(doc(collection(db,'careerEvents')),{eventId:`CAR-${crypto.randomUUID().slice(0,8).toUpperCase()}`,staffUid:req.staffUid,staffId:req.staffId,type:req.type,outcome:'approved',branchId:req.requestedBranchId||null,departmentId:req.requestedDepartmentId||null,rankId:req.requestedRankId||null,reason:decision.reason.trim(),actorUid:actor.uid,ownerOverride:Boolean(decision.ownerOverride),immutable:true,createdAt:serverTimestamp()});}tx.set(doc(collection(db,'auditLogs')),{actorUid:actor.uid,actorType:decision.ownerOverride?'owner':'staff',action:decision.ownerOverride?'career.request.overridden':'career.request.decided',targetType:'career-request',targetId:req.requestId,reason:decision.reason.trim(),immutable:true,createdAt:serverTimestamp()});});}
export function calculateBranchScore(branchId,data){const staff=data.staff.filter(x=>x.branchId===branchId&&x.staffStatus!=='terminated');const loans=data.loans.filter(x=>x.branchId===branchId||x.servicingBranchId===branchId);const apps=data.applications.filter(x=>x.branchId===branchId||x.homeBranchId===branchId);const current=loans.filter(x=>!['delinquent','defaulted'].includes(x.servicingStatus)).length;const quality=loans.length?Math.round(current/loans.length*100):100;const completed=apps.filter(x=>['approved','denied','accepted'].includes(x.status)).length;const operations=Math.min(100,50+completed*5);const staffing=Math.min(100,staff.length*10);const score=Math.round(quality*.5+operations*.3+staffing*.2);return{staff:staff.length,loans:loans.length,applications:apps.length,quality,operations,score};}
