import React,{useEffect,useMemo,useState}from'react';
import{initializeApp,getApps,getApp}from'firebase/app';
import{getAuth,onAuthStateChanged,signOut}from'firebase/auth';
import{getFirestore}from'firebase/firestore';
import{BookOpen,BriefcaseBusiness,Building2,CheckCircle2,ClipboardList,FileText,Gauge,Landmark,LogOut,Megaphone,ShieldCheck,Users}from'lucide-react';
import{completeTask,createAnnouncement,createPolicy,createTask,loadStaffWorkspace,updatePermissions}from'./staffService.js';
import'../styles.css';import'./phase9.css';
const config={apiKey:'AIzaSyCG7LQR2vM2r68Y414jToA1_CDmUE_Ncdw',authDomain:'afg-game.firebaseapp.com',projectId:'afg-game',storageBucket:'afg-game.firebasestorage.app',messagingSenderId:'779966850290',appId:'1:779966850290:web:24f48af23a2e6cae2d9c6b'};
const app=getApps().length?getApp():initializeApp(config),auth=getAuth(app),db=getFirestore(app);
const tabs=[['overview','Overview',Gauge],['work','My Work',ClipboardList],['directory','Directory',Users],['career','My Career',BriefcaseBusiness],['policies','Policies',FileText],['announcements','Announcements',Megaphone],['permissions','Permissions',ShieldCheck]];
const label=v=>(v||'').replaceAll('-',' ').replace(/\b\w/g,m=>m.toUpperCase());
export default function StaffWorkspace(){const[user,setUser]=useState(null),[data,setData]=useState(null),[tab,setTab]=useState('overview'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[task,setTask]=useState({title:'',description:'',assigneeUid:'',priority:'normal'}),[policy,setPolicy]=useState({title:'',body:'',departmentId:'all'}),[announcement,setAnnouncement]=useState({title:'',body:'',audience:'staff'}),[permissionTarget,setPermissionTarget]=useState(''),[permissionText,setPermissionText]=useState('');
async function refresh(uid=user?.uid){if(!uid)return;setData(await loadStaffWorkspace(db,uid));}
useEffect(()=>onAuthStateChanged(auth,async next=>{if(!next){location.href='/signin';return}setUser(next);try{await refresh(next.uid)}catch(e){setError(e.message)}}),[]);
const isOwner=data?.access?.isOwner;const canManage=isOwner||data?.access?.permissions?.includes('staff.manage');
const openTasks=useMemo(()=>data?.tasks?.filter(x=>x.status!=='completed')||[],[data]);
async function act(fn){setBusy(true);setError('');try{await fn();await refresh()}catch(e){setError(e.message)}finally{setBusy(false)}}
if(!user||!data)return <main className="staff-loading"><Landmark/><strong>Apex Financial Group</strong><span>{error||'Loading Staff Workspace…'}</span></main>;
if(!data.access.allowed)return <main className="staff-loading"><ShieldCheck/><strong>Staff access required</strong><span>Your account has not been appointed to AFG staff.</span><a className="button button-dark" href="/careers">Open Careers</a></main>;
const profile=data.profile||{};
return <div className="staff-shell"><aside><a className="staff-brand" href="/"><Landmark/> AFG Staff</a><div className="staff-identity"><small>{profile.staffId||'OWNER'}</small><strong>{profile.rankName||'Founder & Owner'}</strong><span>{profile.position||'Executive Office'}</span></div><nav>{tabs.filter(([id])=>id!=='permissions'||canManage).map(([id,name,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon/>{name}</button>)}</nav><a href="/dashboard">Customer Portal</a><a href="/careers">Careers & HR</a><button onClick={()=>signOut(auth).then(()=>location.href='/')}><LogOut/>Sign out</button></aside><main><header><div><span>PHASE 9</span><h1>Staff Workspace</h1><p>Rank-aware operations, career information, internal work, policy access, and permissions.</p></div><span className="staff-status">{label(profile.staffStatus||'active')}</span></header>{error&&<div className="form-alert">{error}</div>}
{tab==='overview'&&<><section className="staff-metrics"><article><small>Rank</small><strong>{profile.rankName||'Founder & Owner'}</strong><span>{profile.position||'Executive Leadership'}</span></article><article><small>Department</small><strong>{label(profile.departmentId||'executive-office')}</strong><span>{label(profile.branchId||'capital')}</span></article><article><small>Open tasks</small><strong>{openTasks.length}</strong><span>{data.tasks.length} total assignments</span></article><article><small>Required training</small><strong>{data.training.filter(x=>x.status!=='completed').length}</strong><span>{profile.probationStatus?`Probation: ${label(profile.probationStatus)}`:'Active standing'}</span></article></section><section className="staff-grid"><article className="staff-panel"><h2>Current assignments</h2>{openTasks.slice(0,5).map(x=><div className="staff-row" key={x.id}><span><strong>{x.title}</strong><small>{label(x.priority)} · {label(x.status)}</small></span><button disabled={busy} onClick={()=>act(()=>completeTask(db,x.id,user.uid))}>Complete</button></div>)}{!openTasks.length&&<p>No open tasks.</p>}</article><article className="staff-panel"><h2>Latest announcements</h2>{data.announcements.slice(0,5).map(x=><div className="staff-row" key={x.id}><span><strong>{x.title}</strong><small>{x.body}</small></span></div>)}{!data.announcements.length&&<p>No announcements.</p>}</article></section></>}
{tab==='work'&&<section className="staff-panel"><h2>My Work</h2>{data.tasks.map(x=><div className="staff-row" key={x.id}><span><strong>{x.title}</strong><small>{x.description||'No description'} · {label(x.status)}</small></span>{x.status!=='completed'&&<button onClick={()=>act(()=>completeTask(db,x.id,user.uid))}>Complete</button>}</div>)}</section>}
{tab==='directory'&&<section className="staff-panel"><h2>Staff Directory</h2><div className="directory-grid">{data.directory.map(x=><article key={x.uid}><strong>{x.displayName||x.staffId}</strong><span>{x.staffId}</span><small>{x.rankName} · {x.position}</small><small>{label(x.departmentId)} · {label(x.branchId)}</small></article>)}</div></section>}
{tab==='career'&&<section className="staff-grid"><article className="staff-panel"><h2>Career Profile</h2><dl><div><dt>Staff ID</dt><dd>{profile.staffId}</dd></div><div><dt>Rank</dt><dd>{profile.rankName}</dd></div><div><dt>Position</dt><dd>{profile.position}</dd></div><div><dt>Department</dt><dd>{label(profile.departmentId)}</dd></div><div><dt>Branch</dt><dd>{label(profile.branchId)}</dd></div><div><dt>Status</dt><dd>{label(profile.staffStatus)}</dd></div></dl></article><article className="staff-panel"><h2>Training</h2>{data.training.map(x=><div className="staff-row" key={x.id}><span><strong>{label(x.type)}</strong><small>{label(x.status)} · {(x.courses||[]).length} courses</small></span></div>)}</article></section>}
{tab==='policies'&&<><section className="staff-panel"><h2>Policy Center</h2>{data.policies.map(x=><details key={x.id}><summary>{x.title}<small>{x.policyNumber||'AFG Policy'} · Version {x.version||1}</small></summary><p>{x.body}</p></details>)}</section>{canManage&&<section className="staff-panel staff-form"><h2>Create policy</h2><input placeholder="Policy title" value={policy.title} onChange={e=>setPolicy({...policy,title:e.target.value})}/><textarea placeholder="Policy body" value={policy.body} onChange={e=>setPolicy({...policy,body:e.target.value})}/><button className="button button-dark" disabled={busy} onClick={()=>act(async()=>{await createPolicy(db,user.uid,policy);setPolicy({title:'',body:'',departmentId:'all'})})}>Publish policy</button></section>}</>}
{tab==='announcements'&&<><section className="staff-panel"><h2>Internal Announcements</h2>{data.announcements.map(x=><article className="announcement" key={x.id}><strong>{x.title}</strong><p>{x.body}</p><small>{label(x.audience)}</small></article>)}</section>{canManage&&<section className="staff-panel staff-form"><h2>Post announcement</h2><input placeholder="Title" value={announcement.title} onChange={e=>setAnnouncement({...announcement,title:e.target.value})}/><textarea placeholder="Message" value={announcement.body} onChange={e=>setAnnouncement({...announcement,body:e.target.value})}/><button className="button button-dark" onClick={()=>act(async()=>{await createAnnouncement(db,user.uid,announcement);setAnnouncement({title:'',body:'',audience:'staff'})})}>Publish announcement</button></section>}</>}
{tab==='permissions'&&canManage&&<section className="staff-grid"><article className="staff-panel staff-form"><h2>Assign task</h2><select value={task.assigneeUid} onChange={e=>setTask({...task,assigneeUid:e.target.value})}><option value="">Select staff member</option>{data.directory.map(x=><option key={x.uid} value={x.uid}>{x.staffId} — {x.displayName||x.position}</option>)}</select><input placeholder="Task title" value={task.title} onChange={e=>setTask({...task,title:e.target.value})}/><textarea placeholder="Task description" value={task.description} onChange={e=>setTask({...task,description:e.target.value})}/><button className="button button-dark" onClick={()=>act(async()=>{await createTask(db,user.uid,task);setTask({title:'',description:'',assigneeUid:'',priority:'normal'})})}>Assign task</button></article><article className="staff-panel staff-form"><h2>Permission manager</h2><select value={permissionTarget} onChange={e=>{setPermissionTarget(e.target.value);const found=data.directory.find(x=>x.uid===e.target.value);setPermissionText((found?.permissions||[]).join('\n'))}}><option value="">Select staff member</option>{data.directory.map(x=><option key={x.uid} value={x.uid}>{x.staffId} — {x.displayName||x.position}</option>)}</select><textarea placeholder="One permission per line" value={permissionText} onChange={e=>setPermissionText(e.target.value)}/><button className="button button-dark" onClick={()=>act(()=>updatePermissions(db,user.uid,permissionTarget,permissionText.split('\n').map(x=>x.trim()).filter(Boolean)))}>Save permissions</button><p>Owner access cannot be removed. Exact website capabilities come from these protected permission records.</p></article></section>}</main></div>}
