import{addDoc,collection,doc,getDoc,getDocs,serverTimestamp,setDoc,updateDoc}from'firebase/firestore';
const map=s=>s.docs.map(d=>({id:d.id,...d.data()}));
const code=p=>`${p}-${crypto.randomUUID().slice(0,8).toUpperCase()}`;
export const ECONOMIC_CLIMATES=['stable-growth','rapid-growth','inflation','recession','housing-boom','housing-decline','credit-tightening','business-expansion','investment-surge'];
export async function loadOwnerCenter(db,uid){
 const bootstrap=await getDoc(doc(db,'system','bootstrap'));const allowed=bootstrap.exists()&&bootstrap.data().ownerUid===uid;if(!allowed)return{allowed:false};
 const names=['users','staffProfiles','applications','loans','businesses','properties','investments','insuranceClaims','branches','departments','auditLogs','ownerOverrides','institutionEvents','achievements'];
 const results=await Promise.all(names.map(async n=>{try{return map(await getDocs(collection(db,n)))}catch{return[]}}));const data=Object.fromEntries(names.map((n,i)=>[n,results[i]]));
 const[settings,economy]=await Promise.all([getDoc(doc(db,'systemSettings','main')),getDoc(doc(db,'economicSettings','current'))]);
 return{allowed:true,bootstrap:bootstrap.data(),settings:settings.exists()?settings.data():{},economy:economy.exists()?economy.data():{},...data};
}
export async function updateSystemControls(db,uid,data){await setDoc(doc(db,'systemSettings','main'),{registrationEnabled:Boolean(data.registrationEnabled),maintenanceMode:Boolean(data.maintenanceMode),publicVerificationEnabled:Boolean(data.publicVerificationEnabled),institutionNewsEnabled:Boolean(data.institutionNewsEnabled),updatedBy:uid,updatedAt:serverTimestamp()},{merge:true});await addDoc(collection(db,'auditLogs'),{actorUid:uid,actorType:'owner',action:'system.controls.updated',targetType:'system',targetId:'main',reason:'Owner updated institution controls',immutable:true,createdAt:serverTimestamp()});}
export async function updateEconomy(db,uid,data){await setDoc(doc(db,'economicSettings','current'),{climate:data.climate,baseInterestRate:Number(data.baseInterestRate||0),inflationRate:Number(data.inflationRate||0),propertyModifier:Number(data.propertyModifier||1),investmentModifier:Number(data.investmentModifier||1),businessModifier:Number(data.businessModifier||1),loanAvailability:data.loanAvailability||'normal',effectiveAt:serverTimestamp(),updatedBy:uid,updatedAt:serverTimestamp()},{merge:true});await addDoc(collection(db,'auditLogs'),{actorUid:uid,actorType:'owner',action:'economy.settings.updated',targetType:'economy',targetId:'current',reason:`Economic climate changed to ${data.climate}`,immutable:true,createdAt:serverTimestamp()});}
export async function createInstitutionEvent(db,uid,data){if(data.title.trim().length<3||data.description.trim().length<15)throw new Error('Enter a complete event title and description.');await addDoc(collection(db,'institutionEvents'),{eventId:code('EVT'),title:data.title.trim(),description:data.description.trim(),eventType:data.eventType||'institution',startsAt:data.startsAt||null,endsAt:data.endsAt||null,status:data.status||'scheduled',modifierType:data.modifierType||'none',modifierValue:Number(data.modifierValue||0),createdBy:uid,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});}
export async function createAchievement(db,uid,data){if(data.name.trim().length<3||data.description.trim().length<10)throw new Error('Enter a complete achievement.');await addDoc(collection(db,'achievements'),{achievementId:code('ACH'),name:data.name.trim(),description:data.description.trim(),category:data.category||'customer',points:Number(data.points||0),badge:data.badge||'award',active:true,createdBy:uid,createdAt:serverTimestamp()});}
export async function recordOwnerOverride(db,uid,data){if(data.reason.trim().length<10)throw new Error('A detailed override reason is required.');const record={overrideId:code('OVR'),actorUid:uid,targetCollection:data.targetCollection.trim(),targetId:data.targetId.trim(),field:data.field.trim(),previousValue:data.previousValue||null,newValue:data.newValue||null,reason:data.reason.trim(),status:'recorded',immutable:true,createdAt:serverTimestamp()};await addDoc(collection(db,'ownerOverrides'),record);await addDoc(collection(db,'auditLogs'),{actorUid:uid,actorType:'owner',action:'owner.override.recorded',targetType:record.targetCollection,targetId:record.targetId,reason:record.reason,immutable:true,createdAt:serverTimestamp()});}
export function verifyRecord(data,query){const q=query.trim().toLowerCase();if(!q)return[];const sources=[...data.users.map(x=>({type:'Customer',id:x.customerId,name:x.displayName||x.username,status:x.accountStatus})),...data.staffProfiles.map(x=>({type:'Staff',id:x.staffId,name:x.position,status:x.staffStatus})),...data.businesses.map(x=>({type:'Business',id:x.businessId,name:x.name,status:x.status}))];return sources.filter(x=>String(x.id||'').toLowerCase()===q||String(x.name||'').toLowerCase().includes(q)).slice(0,10);}
