import React,{useEffect,useMemo,useState}from'react';
import{getApp,getApps,initializeApp}from'firebase/app';
import{getAuth,onAuthStateChanged,signOut}from'firebase/auth';
import{getFirestore}from'firebase/firestore';
import{Activity,AlertTriangle,Award,Banknote,Building2,CalendarDays,Cog,Database,Landmark,LineChart,LogOut,RefreshCw,Search,ShieldCheck,SlidersHorizontal,Users}from'lucide-react';
import{applyEconomyEvent,createAchievement,createInstitutionEvent,createPropertyIncident,distributePayroll,ECONOMIC_CLIMATES,ECONOMY_EVENT_TARGETS,loadOwnerCenter,PROPERTY_INCIDENT_TYPES,PROPERTY_SEVERITIES,recordOwnerOverride,updateEconomy,updateSystemControls,verifyRecord}from'./adminService.js';
import'../styles.css';import'../stabilization.css';import'./phase14.css';

const config={apiKey:'AIzaSyCG7LQR2vM2r68Y414jToA1_CDmUE_Ncdw',authDomain:'afg-game.firebaseapp.com',projectId:'afg-game',storageBucket:'afg-game.firebasestorage.app',messagingSenderId:'779966850290',appId:'1:779966850290:web:24f48af23a2e6cae2d9c6b'};
const app=getApps().length?getApp():initializeApp(config),auth=getAuth(app),db=getFirestore(app);
const label=v=>String(v||'').split('-').map(x=>x?x[0].toUpperCase()+x.slice(1):'').join(' ');
const money=v=>`$${Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const base=import.meta.env.BASE_URL.replace(/\/$/,'');const go=p=>`${base}${p}`;

export default function OwnerControlCenter(){
 const[user,setUser]=useState(null),[data,setData]=useState(null),[tab,setTab]=useState('overview'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[verify,setVerify]=useState('');
 const[system,setSystem]=useState({registrationEnabled:true,maintenanceMode:false,publicVerificationEnabled:true,institutionNewsEnabled:true});
 const[economy,setEconomy]=useState({climate:'stable-growth',baseInterestRate:5,inflationRate:2,propertyModifier:1,investmentModifier:1,businessModifier:1,loanAvailability:'normal',businessBasePrice:500,propertyBasePrice:5000,insuranceSetupFee:100,insurancePremiumRate:.02});
 const[event,setEvent]=useState({title:'',description:'',eventType:'institution',status:'scheduled',startsAt:'',endsAt:'',modifierType:'none',modifierValue:0});
 const[economyEvent,setEconomyEvent]=useState({title:'',description:'',target:'properties',percentChange:-10});
 const[incident,setIncident]=useState({propertyDocId:'',title:'',incidentType:'fire',severity:'moderate',description:'',valueLossPercent:10,conditionAfter:'damaged',claimEligible:true});
 const[achievement,setAchievement]=useState({name:'',description:'',category:'customer',points:100,badge:'award'});
 const[override,setOverride]=useState({targetCollection:'',targetId:'',field:'',previousValue:'',newValue:'',reason:''});
 const[payroll,setPayroll]=useState({mode:'one',target:'',amount:'',description:'AFG payroll payment'});

 async function refresh(uid=user?.uid){if(!uid)return;const next=await loadOwnerCenter(db,uid);setData(next);setSystem(s=>({...s,...next.settings}));setEconomy(e=>({...e,...next.economy}))}
 useEffect(()=>onAuthStateChanged(auth,async u=>{if(!u){location.href=go('/signin');return}setUser(u);try{await refresh(u.uid)}catch(e){setError(e.message)}}),[]);
 const verification=useMemo(()=>data?verifyRecord(data,verify):[],[data,verify]);
 async function act(fn,clear,message='Saved successfully.'){setBusy(true);setError('');setSuccess('');try{const result=await fn();if(clear)clear();setSuccess(typeof message==='function'?message(result):message);await refresh();return result}catch(e){setError(e.message)}finally{setBusy(false)}}
 if(!user||!data)return <main className="admin-loading"><Landmark/><strong>Apex Financial Group</strong><span>Loading Owner Control Center…</span></main>;
 if(!data.allowed)return <main className="admin-loading"><ShieldCheck/><strong>Founder and Owner access required</strong><a href={go('/')}>Return home</a></main>;

 const metrics=[['Customers',data.users.length,Users],['Staff',data.staffProfiles.length,ShieldCheck],['Applications',data.applications.length,Database],['Active loans',data.loans.filter(x=>x.status==='active').length,Activity],['Businesses',data.businesses.length,Building2],['Economy events',data.economyEvents.length,LineChart]];
 const tabs=[['overview','Overview',Activity],['payroll','Payroll',Banknote],['controls','System Controls',SlidersHorizontal],['economy','Economy & Pricing',Landmark],['economy-events','Economy Events',LineChart],['property-incidents','Property Incidents',AlertTriangle],['events','Institution Events',CalendarDays],['achievements','Achievements',Award],['verification','Verification',Search],['overrides','Overrides',ShieldCheck]];

 return <div className="admin-shell"><aside><a href={go('/')} className="admin-brand"><Landmark/> AFG</a>{tabs.map(([id,name,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon/>{name}</button>)}<a href={go('/account-management')}><Cog/> Account Management</a><a href={go('/staff-management')}><Users/> Staff Management</a><a href={go('/staff')}><Users/> Staff Workspace</a><a href={go('/departments')}><Building2/> Departments</a><button onClick={()=>signOut(auth).then(()=>location.href=go('/'))}><LogOut/> Sign out</button></aside><main>
 <header><div><small>AFG EXECUTIVE ADMINISTRATION</small><h1>Owner Control Center</h1><p>Institution authority, pricing, economic events, incidents, payroll, and oversight.</p></div><button onClick={()=>refresh()}><RefreshCw/> Refresh</button></header>{error&&<div className="admin-alert">{error}</div>}{success&&<div className="banking-success">{success}</div>}

 {tab==='overview'&&<><section className="admin-metrics">{metrics.map(([n,v,I])=><article key={n}><I/><span><small>{n}</small><strong>{v}</strong></span></article>)}</section><section className="admin-grid"><article><h2>Institution status</h2><p><b>Registration:</b> {system.registrationEnabled?'Open':'Closed'}</p><p><b>Maintenance:</b> {system.maintenanceMode?'Enabled':'Disabled'}</p><p><b>Economic climate:</b> {label(economy.climate)}</p><p><b>Business setup:</b> {money(economy.businessBasePrice)}</p><p><b>Property base:</b> {money(economy.propertyBasePrice)}</p></article><article><h2>Direct systems</h2><div className="admin-links">{[['Customer Portal','/dashboard'],['Account Management','/account-management'],['Staff Management','/staff-management'],['Lending','/lending'],['Loans','/loans'],['Academy','/academy-center'],['Economy','/economy-center'],['Departments','/departments']].map(x=><a href={go(x[1])} key={x[0]}>{x[0]}</a>)}</div></article></section></>}

 {tab==='payroll'&&<section className="admin-card"><h2>Customer payroll</h2><p>Credit one customer or every active customer with the same fictional payment amount.</p><label>Who should be paid?<select value={payroll.mode} onChange={e=>setPayroll({...payroll,mode:e.target.value})}><option value="one">One customer</option><option value="all">All active customers</option></select></label>{payroll.mode==='one'&&<label>Customer ID, username, or exact display name<input value={payroll.target} onChange={e=>setPayroll({...payroll,target:e.target.value})} placeholder="CUS-XXXXXX or username"/></label>}<label>Amount per person<input type="number" min="0.01" max="100000" step="0.01" value={payroll.amount} onChange={e=>setPayroll({...payroll,amount:e.target.value})}/></label><label>Payment description<input value={payroll.description} onChange={e=>setPayroll({...payroll,description:e.target.value})}/></label><button disabled={busy||!payroll.amount||(payroll.mode==='one'&&!payroll.target.trim())} onClick={()=>act(()=>distributePayroll(db,user.uid,data,payroll),null,r=>`Payroll ${r.runId} paid ${r.count} customer(s), totaling ${money(r.total)}.`)}>Distribute payroll</button></section>}

 {tab==='controls'&&<section className="admin-card"><h2>System controls</h2>{['registrationEnabled','maintenanceMode','publicVerificationEnabled','institutionNewsEnabled'].map(k=><label className="toggle" key={k}><input type="checkbox" checked={Boolean(system[k])} onChange={e=>setSystem({...system,[k]:e.target.checked})}/><span>{label(k)}</span></label>)}<button disabled={busy} onClick={()=>act(()=>updateSystemControls(db,user.uid,system),null,'System controls updated.')}>Save controls</button></section>}

 {tab==='economy'&&<section className="admin-card"><h2>Economy & setup pricing</h2><label>Climate<select value={economy.climate} onChange={e=>setEconomy({...economy,climate:e.target.value})}>{ECONOMIC_CLIMATES.map(x=><option key={x} value={x}>{label(x)}</option>)}</select></label>{['baseInterestRate','inflationRate','propertyModifier','investmentModifier','businessModifier'].map(k=><label key={k}>{label(k)}<input type="number" step="0.1" value={economy[k]} onChange={e=>setEconomy({...economy,[k]:e.target.value})}/></label>)}<div className="admin-pricing-grid"><label>Business setup base price<input type="number" min="0" value={economy.businessBasePrice} onChange={e=>setEconomy({...economy,businessBasePrice:e.target.value})}/></label><label>Property base price<input type="number" min="1" value={economy.propertyBasePrice} onChange={e=>setEconomy({...economy,propertyBasePrice:e.target.value})}/></label><label>Insurance setup fee<input type="number" min="0" value={economy.insuranceSetupFee} onChange={e=>setEconomy({...economy,insuranceSetupFee:e.target.value})}/></label><label>Insurance premium rate<input type="number" min="0" max="1" step=".001" value={economy.insurancePremiumRate} onChange={e=>setEconomy({...economy,insurancePremiumRate:e.target.value})}/><small>0.02 = 2%</small></label></div><label>Loan availability<select value={economy.loanAvailability} onChange={e=>setEconomy({...economy,loanAvailability:e.target.value})}><option>expanded</option><option>normal</option><option>restricted</option></select></label><button disabled={busy} onClick={()=>act(()=>updateEconomy(db,user.uid,economy),null,'Economy pricing published.')}>Publish economy settings</button></section>}

 {tab==='economy-events'&&<section className="admin-card"><h2>Economy event engine</h2><p>Apply a live percentage change across all currently owned properties, businesses, or investments. Every affected owner is notified.</p><label>Event title<input value={economyEvent.title} onChange={e=>setEconomyEvent({...economyEvent,title:e.target.value})} placeholder="Example: Regional housing boom"/></label><label>Description<textarea value={economyEvent.description} onChange={e=>setEconomyEvent({...economyEvent,description:e.target.value})}/></label><label>Affected system<select value={economyEvent.target} onChange={e=>setEconomyEvent({...economyEvent,target:e.target.value})}>{ECONOMY_EVENT_TARGETS.map(x=><option key={x} value={x}>{label(x)}</option>)}</select></label><label>Percent change<input type="number" min="-95" max="500" step="1" value={economyEvent.percentChange} onChange={e=>setEconomyEvent({...economyEvent,percentChange:e.target.value})}/></label><div className="admin-summary"><b>Impact:</b> {Number(economyEvent.percentChange)>0?'+':''}{economyEvent.percentChange}% on every current {economyEvent.target} record.</div><button disabled={busy} onClick={()=>act(()=>applyEconomyEvent(db,user.uid,economyEvent),()=>setEconomyEvent({title:'',description:'',target:'properties',percentChange:-10}),r=>`Economy event applied to ${r.count} record(s).`)}>Apply economy event</button><div className="record-list">{data.economyEvents.slice().reverse().slice(0,20).map(x=><article key={x.id}><b>{x.title}</b><span>{label(x.target)} · {Number(x.percentChange)>0?'+':''}{x.percentChange}% · {x.affectedRecords} affected</span><p>{x.description}</p></article>)}</div></section>}

 {tab==='property-incidents'&&<section className="admin-card property-incident-console"><h2>Property incident & disaster console</h2><p>Create a specific incident against a customer-owned property. It can change condition, reduce value, notify the owner, and support an insurance claim.</p><label>Affected property<select value={incident.propertyDocId} onChange={e=>setIncident({...incident,propertyDocId:e.target.value})}><option value="">Choose a property</option>{data.properties.map(p=><option value={p.id} key={p.id}>{p.propertyId} · {p.name} · {money(p.currentValue)} · {p.customerId}</option>)}</select></label><div className="admin-pricing-grid"><label>Incident type<select value={incident.incidentType} onChange={e=>setIncident({...incident,incidentType:e.target.value})}>{PROPERTY_INCIDENT_TYPES.map(x=><option value={x} key={x}>{label(x)}</option>)}</select></label><label>Severity<select value={incident.severity} onChange={e=>setIncident({...incident,severity:e.target.value})}>{PROPERTY_SEVERITIES.map(x=><option value={x} key={x}>{label(x)}</option>)}</select></label><label>Resulting condition<select value={incident.conditionAfter} onChange={e=>setIncident({...incident,conditionAfter:e.target.value})}><option value="good">Good</option><option value="fair">Fair</option><option value="damaged">Damaged</option><option value="critical">Critical</option><option value="destroyed">Destroyed</option></select></label><label>Property value loss %<input type="number" min="0" max="100" value={incident.valueLossPercent} onChange={e=>setIncident({...incident,valueLossPercent:e.target.value})}/></label></div><label>Event title<input value={incident.title} onChange={e=>setIncident({...incident,title:e.target.value})}/></label><label>Incident description<textarea value={incident.description} onChange={e=>setIncident({...incident,description:e.target.value})}/></label><button disabled={busy||!incident.propertyDocId} onClick={()=>act(()=>createPropertyIncident(db,user.uid,incident),()=>setIncident({propertyDocId:'',title:'',incidentType:'fire',severity:'moderate',description:'',valueLossPercent:10,conditionAfter:'damaged',claimEligible:true}),'Property incident created and owner notified.')}>Create property incident</button><div className="record-list">{data.propertyIncidents.slice().reverse().slice(0,20).map(x=><article key={x.id}><b>{x.title}</b><span>{x.propertyId} · {label(x.severity)} · {x.valueLossPercent}% loss</span><p>{x.description}</p></article>)}</div></section>}

 {tab==='events'&&<section className="admin-card"><h2>Create institution event</h2><label>Title<input value={event.title} onChange={e=>setEvent({...event,title:e.target.value})}/></label><label>Description<textarea value={event.description} onChange={e=>setEvent({...event,description:e.target.value})}/></label><label>Event type<input value={event.eventType} onChange={e=>setEvent({...event,eventType:e.target.value})}/></label><label>Starts at<input type="datetime-local" value={event.startsAt} onChange={e=>setEvent({...event,startsAt:e.target.value})}/></label><label>Ends at<input type="datetime-local" value={event.endsAt} onChange={e=>setEvent({...event,endsAt:e.target.value})}/></label><button disabled={busy} onClick={()=>act(()=>createInstitutionEvent(db,user.uid,event),()=>setEvent({title:'',description:'',eventType:'institution',status:'scheduled',startsAt:'',endsAt:'',modifierType:'none',modifierValue:0}),'Institution event created.')}>Create event</button></section>}

 {tab==='achievements'&&<section className="admin-card"><h2>Achievement builder</h2>{['name','description','category','points','badge'].map(k=><label key={k}>{label(k)}<input type={k==='points'?'number':'text'} value={achievement[k]} onChange={e=>setAchievement({...achievement,[k]:e.target.value})}/></label>)}<button disabled={busy} onClick={()=>act(()=>createAchievement(db,user.uid,achievement),()=>setAchievement({name:'',description:'',category:'customer',points:100,badge:'award'}),'Achievement created.')}>Create achievement</button></section>}
 {tab==='verification'&&<section className="admin-card"><h2>Institution verification</h2><label>Customer, Staff, or Business ID<input value={verify} onChange={e=>setVerify(e.target.value)} placeholder="CUS-, STF-, or BUS-"/></label><div className="record-list">{verification.map((x,i)=><article key={i}><b>{x.type}: {x.name||'Unnamed record'}</b><span>{x.id} · {label(x.status)}</span></article>)}</div></section>}
 {tab==='overrides'&&<section className="admin-card"><h2>Global override ledger</h2>{Object.keys(override).map(k=><label key={k}>{label(k)}{k==='reason'?<textarea value={override[k]} onChange={e=>setOverride({...override,[k]:e.target.value})}/>:<input value={override[k]} onChange={e=>setOverride({...override,[k]:e.target.value})}/>}</label>)}<button disabled={busy} onClick={()=>act(()=>recordOwnerOverride(db,user.uid,override),()=>setOverride({targetCollection:'',targetId:'',field:'',previousValue:'',newValue:'',reason:''}),'Override recorded.')}>Record override</button></section>}
 </main></div>;
}
